services:
  hub:
    image: seleniarm/hub:4.20.0
  chrome:
    image: seleniarm/node-chromium:124.0
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env

  firefox:
    image: seleniarm/node-firefox:125.0
    shm_size: 2gb
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file: .env
